name: Android Nightly

on:
  push:
    paths:
      - 'android/**'
      - 'lib/**'
      - 'lang/**'
      - 'fonts/**'
      - 'pubspec*'
      - 'pigeons/**'
      - 'test/**'
      - '.github/workflows/nightly.yml'
  workflow_dispatch:
jobs:
  build:
    environment: Nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/build-cache
            ~/fvm
          key: ${{ runner.os }}-pub-gradle-android-fvm-${{ hashFiles('**/pubspec.lock', '**/*.gradle', '**/pom.xml', '**/.fvmrc') }}
          restore-keys: |
            ${{ runner.os }}-pub-gradle-android-fvm-

      - uses: dart-lang/setup-dart@v1.4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - run: dart pub global activate fvm
      - run: echo $KEY_JKS | base64 -d > android/key.jks
        env:
          KEY_JKS: ${{ secrets.KEY_JKS }}
      - run: fvm install
      - run: fvm flutter pub get
      - run: fvm flutter analyze
        continue-on-error: true
#      - name: Flutter test
#        continue-on-error: true
#        run: fvm flutter test
      - run: fvm flutter build apk --debug
        env:
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NIGHTLY: 'true'
      - uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: build/app/outputs/apk/debug/app-debug.apk
#      - name: Upload golden failures
#        uses: actions/upload-artifact@v4
#        with:
#          name: goldens-failures
#          path: test/components/failures/
#          if-no-files-found: 'ignore'
